[project]
name = "silentfrog"
version = "0.1.2"
description = ""
authors = [
    {name = "Developeter",email = "developeter.apps@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyqt5 (==5.15.11)",
    "pyqt5-qt5 (==5.15.2)",
    "pyqt5-sip (>=12.11,<13)",
    "pandas (>=2.2.3,<3.0.0)",
    "urllib3 (>=2.4.0,<3.0.0)",
    "requests (>=2.32.3,<3.0.0)",
    "openpyxl (>=3.1)",
    "httpx[http2] (>=0.28.1,<0.29.0)",
    "beautifulsoup4 (>=4.13.4,<5.0.0)",
    "lxml (>=4.9,<5.0)",
    "tldextract (>=5.3.0,<6.0.0)",
    "xlsxwriter (>=3.2.3,<4.0.0)",
    "aiohttp (>=3.12.0,<4.0.0)",
    "nltk (>=3.9.1,<4.0.0)",
    "pillow (>=11.2.1,<12.0.0)",
    "humanize (>=4.12.3,<5.0.0)"
]

[tool.poetry]
packages = [{include = "silentfrog", from = "src"}]


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
requests-mock = "^1.12.1"
nltk = "^3.9.1"
pytest-asyncio = "^1.0.0"
pytest-aiohttp = "^1.1.0"
pytest-qt = "^4.4.0"
extruct = "^0.16.0"
w3lib = "^2.1.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
silentfrog = "silentfrog.gui:main"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
