"""llms.txt generator (v3 G10 — half B, the GENERATOR).

Proposes an llms.txt (llmstxt.org shape) from a completed Site Crawl: an H1
title, a blockquote summary, and H2 sections of ``- Label: URL`` links
grouped by each page's first path segment. Only INDEXABLE, successfully
crawled pages are listed — the same split ``exporters/html_report.py`` uses
between a pure builder (``build_llms_txt``) and a thin exporter that streams
the crawl exactly once (``export_llms_txt``).

Every crawl-derived string that lands on its own file line (the H1 title,
the summary, a link label) is newline-collapsed first: a hostile page
``<title>`` spanning multiple physical lines could otherwise inject a fake
``#``/``##`` heading line at column 0 of the generated file.
"""

from __future__ import annotations

from collections import defaultdict
from collections.abc import Sequence
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

from ..crawl_run_repository import stream_report_results
from ..site_crawl_types import SiteCrawlReport, SiteCrawlResult

_MAX_SECTIONS = 12
_MAX_LINKS_PER_SECTION = 20
_NEUTRAL_SUMMARY = "Curated page index for AI assistants — generated by Silentfrog."
_INDEXABLE_PREFIX = "Indexable"


def build_llms_txt(report: SiteCrawlReport, results: Sequence[SiteCrawlResult]) -> str:
    """Pure derivation: propose an llms.txt string from a completed crawl."""
    eligible = [result for result in results if result.indexability.startswith(_INDEXABLE_PREFIX)]
    home = _home_result(report, eligible)
    lines = [
        f"# {_sanitize(_site_title(report, home))}",
        "",
        f"> {_sanitize(_summary(home))}",
    ]
    for label, section_results in _sections(eligible):
        lines.append("")
        lines.append(f"## {label}")
        lines.append("")
        lines.extend(_section_links(section_results))
    return "\n".join(lines).rstrip("\n") + "\n"


def export_llms_txt(report: SiteCrawlReport, file_path: Path) -> None:
    file_path = Path(file_path)
    file_path.parent.mkdir(parents=True, exist_ok=True)
    # Stream the crawl exactly once (H1/H2 convention): the same materialized
    # list backs section grouping and the home-page lookup.
    results = list(stream_report_results(report))
    document = build_llms_txt(report, results)
    file_path.write_text(document, encoding="utf-8")


def _home_result(report: SiteCrawlReport, results: Sequence[SiteCrawlResult]) -> SiteCrawlResult | None:
    base_host = urlparse(report.base_url).netloc.lower()
    for result in results:
        parsed = urlparse(result.url)
        if parsed.netloc.lower() == base_host and parsed.path in ("", "/"):
            return result
    return None


def _site_title(report: SiteCrawlReport, home: SiteCrawlResult | None) -> str:
    if home is not None and home.title:
        return home.title
    return urlparse(report.base_url).netloc or "Site"


def _meta_value(payload: Any, name: str) -> str:
    # Mirrors exporters/llm_export.py's ``_meta_value`` — small enough that
    # importing a private cross-module helper would cost more than repeating it.
    for row in payload.meta:
        if len(row) > 1 and str(row[0]).strip().lower() == name:
            return str(row[1]).strip()
    return ""


def _summary(home: SiteCrawlResult | None) -> str:
    if home is not None and home.payload is not None:
        description = _meta_value(home.payload, "description")
        if description:
            return description
    return _NEUTRAL_SUMMARY


def _segment_label(url: str) -> str:
    segment = urlparse(url).path.strip("/").split("/", 1)[0]
    if not segment:
        return "Home"
    return segment.replace("-", " ").replace("_", " ").title()


def _sections(results: Sequence[SiteCrawlResult]) -> list[tuple[str, list[SiteCrawlResult]]]:
    grouped: dict[str, list[SiteCrawlResult]] = defaultdict(list)
    for result in results:
        grouped[_segment_label(result.url)].append(result)
    ordered = sorted(grouped.items(), key=lambda item: (-len(item[1]), item[0]))
    return ordered[:_MAX_SECTIONS]


def _entry_line(result: SiteCrawlResult) -> str:
    label = _sanitize(result.title) if result.title else result.url
    return f"- {label}: {result.url}"


def _section_links(results: Sequence[SiteCrawlResult]) -> list[str]:
    ordered = sorted(results, key=lambda result: result.url)[:_MAX_LINKS_PER_SECTION]
    return [_entry_line(result) for result in ordered]


def _sanitize(text: str) -> str:
    """Collapse all whitespace (incl. newlines) to single spaces and trim.

    Prevents a hostile crawl-derived string (page title, meta description)
    from breaking onto a new physical line and forging a ``#``/``##``
    heading or a second ``- `` bullet at column 0.
    """
    return " ".join(text.split())


__all__ = ["build_llms_txt", "export_llms_txt"]
