from __future__ import annotations

import argparse
import os
import platform
import subprocess
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class PackagePaths:
    root: Path
    entrypoint: Path
    build_dir: Path


def package_paths(root: Path, system_name: str | None = None) -> PackagePaths:
    target = (system_name or platform.system()).lower()
    return PackagePaths(
        root=root,
        entrypoint=root / "deploy" / "main.py",
        build_dir=root / "build" / "package" / target,
    )


def package_command(paths: PackagePaths, mode: str, dry_run: bool, keep_files: bool) -> list[str]:
    command = [
        "pyside6-deploy",
        str(paths.entrypoint),
        "--force",
        "--name",
        "Silentfrog",
        "--mode",
        mode,
        "--extra-ignore-dirs",
        ".git,.github,.venv,build,dist,docs,tests,__pycache__",
    ]
    if keep_files:
        command.append("--keep-deployment-files")
    if dry_run:
        command.append("--dry-run")
    return command


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Package Silentfrog with pyside6-deploy")
    parser.add_argument("--mode", choices=("onefile", "standalone"), default="standalone")
    parser.add_argument("--dry-run", action="store_true", help="Print the pyside6-deploy commands without building")
    parser.add_argument(
        "--keep-deployment-files",
        action="store_true",
        help="Preserve intermediate deployment files generated by pyside6-deploy",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    root = Path(__file__).resolve().parents[1]
    paths = package_paths(root)
    paths.build_dir.mkdir(parents=True, exist_ok=True)
    env = os.environ.copy()
    env.setdefault("QT_API", "pyside6")
    command = package_command(paths, args.mode, args.dry_run, args.keep_deployment_files)
    subprocess.run(command, cwd=paths.build_dir, env=env, check=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
